#
# Local-only Docker Compose override to persist data volumes in the local 'storage' dir.
#

services:

  bcm-links-web:
    restart: "no"
    environment:
      PORT: "${PORT:-3000}"
    volumes:
      - ./storage/app:/data

  bcm-links-browser:
    restart: "no"

  bcm-links-search:
    restart: "no"
    volumes:
      - ./storage/search:/meili_data
